CREATE TABLE EMPLOYEE (
	ID serial NOT NULL PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	CPF VARCHAR(255) NOT NULL,
	hourlyvalue DECIMAL(12,4),
	workinghoursdayvalue DECIMAL(12,4),
	lunchhoursvalue DECIMAL(12,4), 
	profile VARCHAR(255),
	UPDATEDATE DATE,
	CRIATIONDATE DATE,
	COMPANY integer,
	CONSTRAINT EMPLOYEE_company_FKEY FOREIGN KEY (company) REFERENCES company (ID)
);