CREATE TABLE EMPLOYEE (
	ID serial NOT NULL PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	CPF VARCHAR(255) NOT NULL,
	hourlyvalue MONEY,
	workinghoursdayvalue MONEY,
	lunchhoursvalue MONEY, 
	profile VARCHAR(255),
	UPDATEDATE TIMESTAMPTZ NOT NULL,
	CRIATIONDATE TIMESTAMPTZ NOT NULL,
	COMPANY integer,
	CONSTRAINT EMPLOYEE_company_FKEY FOREIGN KEY (company) REFERENCES company (ID)
);