CREATE TABLE REALESE (
	ID serial NOT NULL PRIMARY KEY,
	DESCRIPTION VARCHAR(255) NOT NULL,
	LOCATION VARCHAR(255) NOT NULL,
	UPDATEDATE DATE NOT NULL,
	CRIATIONDATE DATE NOT NULL,
	realesetype VARCHAR(255) NOT NULL,
	EMPLOYEE integer,
	CONSTRAINT REALESE_EMPLOYEE_FKEY FOREIGN KEY (EMPLOYEE) REFERENCES EMPLOYEE (ID)
);